### ISSUE TITLE
Problem with Aydin installation

### ISSUE THREAD

**Issue by maryebrown1** [royerlab/aydin#263]
I get the following code when I try to launch aydin 0.0.15:
``(aydin_env) C:\Users\Mary Brown>aydin
Traceback (most recent call last):
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\Scripts\aydin.exe\__main__.py", line 4, in <module>
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\aydin\cli\cli.py", line 16, in <module>
    from aydin.gui.gui import run
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\aydin\gui\gui.py", line 7, in <module>
    from aydin.gui.main_page import MainPage
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\aydin\gui\main_page.py", line 27, in <module>
    from aydin.gui.tabs.qt.denoising_cropping import DenoisingCroppingTab
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\aydin\gui\tabs\qt\denoising_cropping.py", line 1, in <module>
    from aydin.gui.tabs.qt.base_cropping import BaseCroppingTab
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\aydin\gui\tabs\qt\base_cropping.py", line 2, in <module>
    from napari._qt.qt_viewer import QtViewer
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\_qt\__init__.py", line 6, in <module>
    from ..utils.translations import trans
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\colormaps\__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\colormaps\colormap.py", line 7, in <module>
    from ..events import EventedModel
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\events\__init__.py", line 1, in <module>
    from .event import (  # isort:skip
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\events\event.py", line 73, in <module>
    from ..translations import trans
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\translations.py", line 13, in <module>
    from ._base import _DEFAULT_CONFIG_PATH, _DEFAULT_LOCALE
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\napari\utils\_base.py", line 14, in <module>
    _DEFAULT_CONFIG_PATH = user_config_dir(_APPNAME, _APPAUTHOR, _FILENAME)
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\appdirs.py", line 196, in user_config_dir
    path = user_data_dir(appname, appauthor, None, roaming)
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\appdirs.py", line 81, in user_data_dir
    path = os.path.normpath(_get_win_folder(const))
  File "C:\Users\Mary Brown\.conda\envs\aydin_env\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.

I am not learned in computer coding and I'm not sure how to interpret this. What is wrong with my Aydin 0.1.15 installation? Will you create an exe or msi Windows installation file for this new version of Aydin? Thank you.

**Comment by AhmetCanSolak** [comment]
Hello @maryebrown1 , thank you for reporting the error and using Aydin!

It seems installed pywin32 version causing trouble, installing an earlier version might help, you can do that with `pip install --upgrade pywin32==228`. What's your conda version also?

Yes I will be making the executable for v0.1.15 for Windows later today, will drop the link here. 

Meanwhile let me know if I can help with anything else!

**Comment by maryebrown1** [comment]
Thank you! I'll look for the executable later today.

**Comment by AhmetCanSolak** [comment]
Are you able to use the executable smoothly or same/similar problem still occurs @maryebrown1 ?

**Comment by maryebrown1** [comment]
The executable app works for me! Thank you for your help!

**Comment by AhmetCanSolak** [comment]
glad to hear that @maryebrown1 , I will  close  the issue now but feel free to open a new issue if you  face any other problems,  happy denoising!
