### ISSUE TITLE
cannot convert float NaN to integer

### ISSUE THREAD

**Issue by pent1162** [royerlab/aydin#268]
Traceback (most recent call last):
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\gui\_qt\job_runners\worker.py", line 60, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\gui\_qt\job_runners\denoise_job_runner.py", line 67, in start_func
    denoised = self.denoiser.denoise(
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\restoration\denoise\classic.py", line 349, in denoise
    response = self.it.translate(
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\it\base.py", line 393, in translate
    tilling_strategy, margins = self._get_tilling_strategy_and_margins(
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\it\base.py", line 569, in _get_tilling_strategy_and_margins
    spatiotemp_tilling_strategy = tuple(
  File "C:\Users\xxxxxx\Miniconda3\envs\aydin_env\lib\site-packages\aydin\it\base.py", line 570, in <genexpr>
    max(1, min(rest_split_factor, int(math.ceil(split_per_dim * s))))
**ValueError: cannot convert float NaN to integer**

System:
Intel Xeon Gold 6256 CPU 3.6Ghz
RAM 1TB

Windowns Server 2016 ver1607

![Aydin](https://user-images.githubusercontent.com/17253051/202395988-5accdf43-d74c-4b53-931b-9de09519dcee.jpg)

**Comment by AhmetCanSolak** [comment]
could you share the image file you were using with me @pent1162 ? I would like to reproduce the error to fix it correctly.

**Comment by pent1162** [comment]
[Img](https://www.dropbox.com/s/47lcaijjz1ur0c9/Merged_pos_8.tif?dl=0)
Thanks

**Comment by AhmetCanSolak** [comment]
Hi @pent1162 ,

I realized this is a two-channel image. Trying to denoise a multi-channel image as is won't be my suggestion(models usually have hard time to benefit from correlations across different imaging channels). So I downloaded your image and split its channel. I did it for the first channel, here you can see the result: 
![image](https://user-images.githubusercontent.com/15677695/208556149-04da00d3-6c01-4098-b8e2-5efbf3331d62.png)


Also please let me know what is your training crop selection. If you like to continue on this discussion in private, feel free to send me an email.

**Comment by AhmetCanSolak** [comment]
Happy new year @pent1162 ! I wanted to check if you were able to run Aydin on your image with your computer? Please let me know if there is anything I can help with.

**Comment by pent1162** [comment]
Happy new year. 
It worked well and thanks for your help.
