### ISSUE TITLE
MAC installation with libomp installed

### ISSUE THREAD

**Issue by BioinfoTongLI** [royerlab/aydin#61]
**Describe the bug**
Unable to start AydinStudio even with libomp installed with `brew`.
It seems to me that aydin is looking for the `libomp` in `/usr/local/opt/libomp` instead of `/Users/tl10/homebrew/Cellar/libomp/` where `brew` by default install libraries to ?

**To Reproduce**
1. Following this section: https://royerlab.github.io/aydin/getting_started/install.html#install-aydin-in-a-conda-environment-with-cuda-support
2. Run `aydin` in termal
3. 
```
❯ aydin
<class 'OSError'> dlopen(/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found <traceback object at 0x7f834cb109c0>
Traceback (most recent call last):
  File "/Users/tl10/miniconda3/envs/aydin_env/bin/aydin", line 8, in <module>
    sys.exit(cli())
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/cli/cli.py", line 47, in cli
    run(VERSION)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/gui/gui.py", line 123, in run
    ex = App(ver)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/gui/gui.py", line 37, in __init__
    self.main_widget = MainPage(self, self.threadpool)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/gui/main_page.py", line 60, in __init__
    "Denoise": DenoiseTab(self),
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/gui/tabs/qt/denoise.py", line 63, in __init__
    ) = get_list_of_denoiser_implementations()
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/restoration/denoise/util/denoise_utils.py", line 59, in get_list_of_denoiser_implementations
    descriptions += denoiser_class().implementations_description
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/restoration/denoise/noise2selffgr.py", line 148, in implementations_description
    response = importlib.import_module(regression.__name__ + '.' + module.name)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/aydin/regression/lgbm.py", line 6, in <module>
    import lightgbm
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/tl10/miniconda3/envs/aydin_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```

**Expected behavior**
AydinStudio running with GUI

**Screenshots**
Where the current libomp is installed:
```
❯ brew info libomp
libomp: stable 13.0.0 (bottled)
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/Users/tl10/homebrew/Cellar/libomp/13.0.0 (9 files, 1.6MB) *
  Poured from bottle on 2021-12-14 at 12:15:36
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libomp.rb
License: MIT
```

**Desktop (please complete the following information):**
 - OS:  OSX
 - Version : catalina 10.15.7

**Comment by AhmetCanSolak** [comment]
Thank you for the issue @BioinfoTongLI !

Honestly, I haven't seen before brew can install packages in user's home folder. Did you set it yourself? Both on my mojave and big sur, brew installed the packages under `/usr/local`.

I am trying to reproduce your problem and searching for a way to tell your computer where libomp is installed.

**Comment by AhmetCanSolak** [comment]
btw, @BioinfoTongLI are you using bundled version or installed Aydin with `pip`?

**Comment by BioinfoTongLI** [comment]
> Thank you for the issue @BioinfoTongLI !
> 
> Honestly, I haven't seen before brew can install packages in user's home folder. Did you set it yourself? Both on my mojave and big sur, brew installed the packages under `/usr/local`.
> 
> I am trying to reproduce your problem and searching for a way to tell your computer where libomp is installed.

You might be right. It could be my laptop, it belongs to our institute and I am using  the `brew` distributed by them. 



> btw, @BioinfoTongLI are you using bundled version or installed Aydin with `pip`?
> 
> edit: I guess you got with `pip`, could you try bundled version too?

I am using `pip` version.

Many thanks for your help!

Best,
Tong

**Comment by AhmetCanSolak** [comment]
Could you try to download bundled version: https://github.com/royerlab/aydin/releases/download/v0.1.11/aydin_0.1.11_osx.pkg and let me know if you still get error @BioinfoTongLI ?

**Comment by AhmetCanSolak** [comment]
Could you try to get Aydin bundle installed with your IT @BioinfoTongLI ? We have the required libomp files within our bundle and that might be an easier solution for your case(instead of rerouting things and possibly re-installing brew).

**Comment by BioinfoTongLI** [comment]
Yea, just have it installed. And all seems to be working fine. 
Please feel free to close this as this is quite of an edge case.

**Comment by AhmetCanSolak** [comment]
glad to hear that! I will close the issue now but feel free to re-open if you face same issue or make a new issue if there is anything else I can help with.
